server {
    server_name 2easy-backend.merlionit.com;

    root /home/ubuntu/apps/2easy-ede-web/public;

    access_log /var/log/nginx/2easyedebackend_access.log;
    error_log /var/log/nginx/2easyedebackend_error.log;

    location / {
        proxy_pass http://127.0.0.1:27002;

        proxy_connect_timeout       120s;
        proxy_send_timeout          120s;
        proxy_read_timeout          120s;
        send_timeout                120s;

        client_max_body_size        512M;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
    }
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
       root /usr/share/nginx/html;
    }
}
# sudo ln -s /etc/nginx/sites-available/2easyedebackend /etc/nginx/sites-enabled/
# sudo certbot --nginx -d 2easy-backend.merlionit.com
